#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 28 17:42:56 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=rethinking-voxels_r0.1-beta9.zip
