State:7
VersionVanillaName:1.21.1
VersionArgumentIndieV2:True
VersionVanilla:21.0.1
Info:正式版 1.21.1, NeoForge 21.1.248
VersionNeoForge:21.1.248
IsStar:False
VersionLiteLoader:False
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/NeoForge.png
ReleaseTime:2024-08-08 20:24
